/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/registro` | `/registro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/asistencia` | `/asistencia`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rutinas` | `/rutinas`; params?: Router.UnknownInputParams; } | { pathname: `/clientes/crear`; params?: Router.UnknownInputParams; } | { pathname: `/clientes`; params?: Router.UnknownInputParams; } | { pathname: `/entrenadores/crear`; params?: Router.UnknownInputParams; } | { pathname: `/entrenadores`; params?: Router.UnknownInputParams; } | { pathname: `/clientes/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/entrenadores/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/registro` | `/registro`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/asistencia` | `/asistencia`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/rutinas` | `/rutinas`; params?: Router.UnknownOutputParams; } | { pathname: `/clientes/crear`; params?: Router.UnknownOutputParams; } | { pathname: `/clientes`; params?: Router.UnknownOutputParams; } | { pathname: `/entrenadores/crear`; params?: Router.UnknownOutputParams; } | { pathname: `/entrenadores`; params?: Router.UnknownOutputParams; } | { pathname: `/clientes/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/entrenadores/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/registro${`?${string}` | `#${string}` | ''}` | `/registro${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/asistencia${`?${string}` | `#${string}` | ''}` | `/asistencia${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/rutinas${`?${string}` | `#${string}` | ''}` | `/rutinas${`?${string}` | `#${string}` | ''}` | `/clientes/crear${`?${string}` | `#${string}` | ''}` | `/clientes${`?${string}` | `#${string}` | ''}` | `/entrenadores/crear${`?${string}` | `#${string}` | ''}` | `/entrenadores${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/registro` | `/registro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/asistencia` | `/asistencia`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rutinas` | `/rutinas`; params?: Router.UnknownInputParams; } | { pathname: `/clientes/crear`; params?: Router.UnknownInputParams; } | { pathname: `/clientes`; params?: Router.UnknownInputParams; } | { pathname: `/entrenadores/crear`; params?: Router.UnknownInputParams; } | { pathname: `/entrenadores`; params?: Router.UnknownInputParams; } | `/clientes/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/entrenadores/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/clientes/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/entrenadores/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
